return {
	-- "number",
	-- "relativenumber",
	"expandtab",
	"smartindent",
	"nobackup",
	{ "clipboard", "unnamedplus,unnamed" },
	{ "signcolumn", "yes" },
	{ "wrap", false },
	{ "tabstop", 2 },
	{ "shiftwidth", 2 },
	{ "foldmethod", "expr" },
	{ "foldexpr", "nvim_treesitter#foldexpr()" },
	{ "foldlevel", 99 },
}
